// Code generated by ent, DO NOT EDIT.

package location

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the location type in the database.
	Label = "location"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChrononym holds the string denoting the chrononym field in the database.
	FieldChrononym = "chrononym"
	// FieldDefinition holds the string denoting the definition field in the database.
	FieldDefinition = "definition"
	// FieldContext holds the string denoting the context field in the database.
	FieldContext = "context"
	// FieldDistrict holds the string denoting the district field in the database.
	FieldDistrict = "district"
	// FieldSelsovet holds the string denoting the selsovet field in the database.
	FieldSelsovet = "selsovet"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldDistrictSs holds the string denoting the district_ss field in the database.
	FieldDistrictSs = "district_ss"
	// Table holds the table name of the location in the database.
	Table = "locations"
)

// Columns holds all SQL columns for location fields.
var Columns = []string{
	FieldID,
	FieldChrononym,
	FieldDefinition,
	FieldContext,
	FieldDistrict,
	FieldSelsovet,
	FieldLatitude,
	FieldLongitude,
	FieldComment,
	FieldYear,
	FieldDistrictSs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ChrononymValidator is a validator for the "chrononym" field. It is called by the builders before save.
	ChrononymValidator func(string) error
	// DefinitionValidator is a validator for the "definition" field. It is called by the builders before save.
	DefinitionValidator func(string) error
	// ContextValidator is a validator for the "context" field. It is called by the builders before save.
	ContextValidator func(string) error
	// DistrictValidator is a validator for the "district" field. It is called by the builders before save.
	DistrictValidator func(string) error
	// SelsovetValidator is a validator for the "selsovet" field. It is called by the builders before save.
	SelsovetValidator func(string) error
	// YearValidator is a validator for the "year" field. It is called by the builders before save.
	YearValidator func(string) error
	// DistrictSsValidator is a validator for the "district_ss" field. It is called by the builders before save.
	DistrictSsValidator func(string) error
)

// OrderOption defines the ordering options for the Location queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChrononym orders the results by the chrononym field.
func ByChrononym(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChrononym, opts...).ToFunc()
}

// ByDefinition orders the results by the definition field.
func ByDefinition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefinition, opts...).ToFunc()
}

// ByContext orders the results by the context field.
func ByContext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContext, opts...).ToFunc()
}

// ByDistrict orders the results by the district field.
func ByDistrict(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistrict, opts...).ToFunc()
}

// BySelsovet orders the results by the selsovet field.
func BySelsovet(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelsovet, opts...).ToFunc()
}

// ByLatitude orders the results by the latitude field.
func ByLatitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatitude, opts...).ToFunc()
}

// ByLongitude orders the results by the longitude field.
func ByLongitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongitude, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByDistrictSs orders the results by the district_ss field.
func ByDistrictSs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDistrictSs, opts...).ToFunc()
}
