// Code generated by ent, DO NOT EDIT.

package location

import (
	"entgo.io/ent/dialect/sql"
	"github.com/zeshi09/dialectApi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldID, id))
}

// Chrononym applies equality check predicate on the "chrononym" field. It's identical to ChrononymEQ.
func Chrononym(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldChrononym, v))
}

// Definition applies equality check predicate on the "definition" field. It's identical to DefinitionEQ.
func Definition(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldDefinition, v))
}

// Context applies equality check predicate on the "context" field. It's identical to ContextEQ.
func Context(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldContext, v))
}

// District applies equality check predicate on the "district" field. It's identical to DistrictEQ.
func District(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldDistrict, v))
}

// Selsovet applies equality check predicate on the "selsovet" field. It's identical to SelsovetEQ.
func Selsovet(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldSelsovet, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldLongitude, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldComment, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldYear, v))
}

// DistrictSs applies equality check predicate on the "district_ss" field. It's identical to DistrictSsEQ.
func DistrictSs(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldDistrictSs, v))
}

// ChrononymEQ applies the EQ predicate on the "chrononym" field.
func ChrononymEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldChrononym, v))
}

// ChrononymNEQ applies the NEQ predicate on the "chrononym" field.
func ChrononymNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldChrononym, v))
}

// ChrononymIn applies the In predicate on the "chrononym" field.
func ChrononymIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldChrononym, vs...))
}

// ChrononymNotIn applies the NotIn predicate on the "chrononym" field.
func ChrononymNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldChrononym, vs...))
}

// ChrononymGT applies the GT predicate on the "chrononym" field.
func ChrononymGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldChrononym, v))
}

// ChrononymGTE applies the GTE predicate on the "chrononym" field.
func ChrononymGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldChrononym, v))
}

// ChrononymLT applies the LT predicate on the "chrononym" field.
func ChrononymLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldChrononym, v))
}

// ChrononymLTE applies the LTE predicate on the "chrononym" field.
func ChrononymLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldChrononym, v))
}

// ChrononymContains applies the Contains predicate on the "chrononym" field.
func ChrononymContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldChrononym, v))
}

// ChrononymHasPrefix applies the HasPrefix predicate on the "chrononym" field.
func ChrononymHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldChrononym, v))
}

// ChrononymHasSuffix applies the HasSuffix predicate on the "chrononym" field.
func ChrononymHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldChrononym, v))
}

// ChrononymEqualFold applies the EqualFold predicate on the "chrononym" field.
func ChrononymEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldChrononym, v))
}

// ChrononymContainsFold applies the ContainsFold predicate on the "chrononym" field.
func ChrononymContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldChrononym, v))
}

// DefinitionEQ applies the EQ predicate on the "definition" field.
func DefinitionEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldDefinition, v))
}

// DefinitionNEQ applies the NEQ predicate on the "definition" field.
func DefinitionNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldDefinition, v))
}

// DefinitionIn applies the In predicate on the "definition" field.
func DefinitionIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldDefinition, vs...))
}

// DefinitionNotIn applies the NotIn predicate on the "definition" field.
func DefinitionNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldDefinition, vs...))
}

// DefinitionGT applies the GT predicate on the "definition" field.
func DefinitionGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldDefinition, v))
}

// DefinitionGTE applies the GTE predicate on the "definition" field.
func DefinitionGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldDefinition, v))
}

// DefinitionLT applies the LT predicate on the "definition" field.
func DefinitionLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldDefinition, v))
}

// DefinitionLTE applies the LTE predicate on the "definition" field.
func DefinitionLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldDefinition, v))
}

// DefinitionContains applies the Contains predicate on the "definition" field.
func DefinitionContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldDefinition, v))
}

// DefinitionHasPrefix applies the HasPrefix predicate on the "definition" field.
func DefinitionHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldDefinition, v))
}

// DefinitionHasSuffix applies the HasSuffix predicate on the "definition" field.
func DefinitionHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldDefinition, v))
}

// DefinitionEqualFold applies the EqualFold predicate on the "definition" field.
func DefinitionEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldDefinition, v))
}

// DefinitionContainsFold applies the ContainsFold predicate on the "definition" field.
func DefinitionContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldDefinition, v))
}

// ContextEQ applies the EQ predicate on the "context" field.
func ContextEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldContext, v))
}

// ContextNEQ applies the NEQ predicate on the "context" field.
func ContextNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldContext, v))
}

// ContextIn applies the In predicate on the "context" field.
func ContextIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldContext, vs...))
}

// ContextNotIn applies the NotIn predicate on the "context" field.
func ContextNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldContext, vs...))
}

// ContextGT applies the GT predicate on the "context" field.
func ContextGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldContext, v))
}

// ContextGTE applies the GTE predicate on the "context" field.
func ContextGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldContext, v))
}

// ContextLT applies the LT predicate on the "context" field.
func ContextLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldContext, v))
}

// ContextLTE applies the LTE predicate on the "context" field.
func ContextLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldContext, v))
}

// ContextContains applies the Contains predicate on the "context" field.
func ContextContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldContext, v))
}

// ContextHasPrefix applies the HasPrefix predicate on the "context" field.
func ContextHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldContext, v))
}

// ContextHasSuffix applies the HasSuffix predicate on the "context" field.
func ContextHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldContext, v))
}

// ContextEqualFold applies the EqualFold predicate on the "context" field.
func ContextEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldContext, v))
}

// ContextContainsFold applies the ContainsFold predicate on the "context" field.
func ContextContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldContext, v))
}

// DistrictEQ applies the EQ predicate on the "district" field.
func DistrictEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldDistrict, v))
}

// DistrictNEQ applies the NEQ predicate on the "district" field.
func DistrictNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldDistrict, v))
}

// DistrictIn applies the In predicate on the "district" field.
func DistrictIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldDistrict, vs...))
}

// DistrictNotIn applies the NotIn predicate on the "district" field.
func DistrictNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldDistrict, vs...))
}

// DistrictGT applies the GT predicate on the "district" field.
func DistrictGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldDistrict, v))
}

// DistrictGTE applies the GTE predicate on the "district" field.
func DistrictGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldDistrict, v))
}

// DistrictLT applies the LT predicate on the "district" field.
func DistrictLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldDistrict, v))
}

// DistrictLTE applies the LTE predicate on the "district" field.
func DistrictLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldDistrict, v))
}

// DistrictContains applies the Contains predicate on the "district" field.
func DistrictContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldDistrict, v))
}

// DistrictHasPrefix applies the HasPrefix predicate on the "district" field.
func DistrictHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldDistrict, v))
}

// DistrictHasSuffix applies the HasSuffix predicate on the "district" field.
func DistrictHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldDistrict, v))
}

// DistrictEqualFold applies the EqualFold predicate on the "district" field.
func DistrictEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldDistrict, v))
}

// DistrictContainsFold applies the ContainsFold predicate on the "district" field.
func DistrictContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldDistrict, v))
}

// SelsovetEQ applies the EQ predicate on the "selsovet" field.
func SelsovetEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldSelsovet, v))
}

// SelsovetNEQ applies the NEQ predicate on the "selsovet" field.
func SelsovetNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldSelsovet, v))
}

// SelsovetIn applies the In predicate on the "selsovet" field.
func SelsovetIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldSelsovet, vs...))
}

// SelsovetNotIn applies the NotIn predicate on the "selsovet" field.
func SelsovetNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldSelsovet, vs...))
}

// SelsovetGT applies the GT predicate on the "selsovet" field.
func SelsovetGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldSelsovet, v))
}

// SelsovetGTE applies the GTE predicate on the "selsovet" field.
func SelsovetGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldSelsovet, v))
}

// SelsovetLT applies the LT predicate on the "selsovet" field.
func SelsovetLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldSelsovet, v))
}

// SelsovetLTE applies the LTE predicate on the "selsovet" field.
func SelsovetLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldSelsovet, v))
}

// SelsovetContains applies the Contains predicate on the "selsovet" field.
func SelsovetContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldSelsovet, v))
}

// SelsovetHasPrefix applies the HasPrefix predicate on the "selsovet" field.
func SelsovetHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldSelsovet, v))
}

// SelsovetHasSuffix applies the HasSuffix predicate on the "selsovet" field.
func SelsovetHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldSelsovet, v))
}

// SelsovetEqualFold applies the EqualFold predicate on the "selsovet" field.
func SelsovetEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldSelsovet, v))
}

// SelsovetContainsFold applies the ContainsFold predicate on the "selsovet" field.
func SelsovetContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldSelsovet, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.Location {
	return predicate.Location(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.Location {
	return predicate.Location(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.Location {
	return predicate.Location(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.Location {
	return predicate.Location(sql.FieldNotNull(FieldLongitude))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.Location {
	return predicate.Location(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.Location {
	return predicate.Location(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldComment, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldYear, v))
}

// YearContains applies the Contains predicate on the "year" field.
func YearContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldYear, v))
}

// YearHasPrefix applies the HasPrefix predicate on the "year" field.
func YearHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldYear, v))
}

// YearHasSuffix applies the HasSuffix predicate on the "year" field.
func YearHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldYear, v))
}

// YearEqualFold applies the EqualFold predicate on the "year" field.
func YearEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldYear, v))
}

// YearContainsFold applies the ContainsFold predicate on the "year" field.
func YearContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldYear, v))
}

// DistrictSsEQ applies the EQ predicate on the "district_ss" field.
func DistrictSsEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldEQ(FieldDistrictSs, v))
}

// DistrictSsNEQ applies the NEQ predicate on the "district_ss" field.
func DistrictSsNEQ(v string) predicate.Location {
	return predicate.Location(sql.FieldNEQ(FieldDistrictSs, v))
}

// DistrictSsIn applies the In predicate on the "district_ss" field.
func DistrictSsIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldIn(FieldDistrictSs, vs...))
}

// DistrictSsNotIn applies the NotIn predicate on the "district_ss" field.
func DistrictSsNotIn(vs ...string) predicate.Location {
	return predicate.Location(sql.FieldNotIn(FieldDistrictSs, vs...))
}

// DistrictSsGT applies the GT predicate on the "district_ss" field.
func DistrictSsGT(v string) predicate.Location {
	return predicate.Location(sql.FieldGT(FieldDistrictSs, v))
}

// DistrictSsGTE applies the GTE predicate on the "district_ss" field.
func DistrictSsGTE(v string) predicate.Location {
	return predicate.Location(sql.FieldGTE(FieldDistrictSs, v))
}

// DistrictSsLT applies the LT predicate on the "district_ss" field.
func DistrictSsLT(v string) predicate.Location {
	return predicate.Location(sql.FieldLT(FieldDistrictSs, v))
}

// DistrictSsLTE applies the LTE predicate on the "district_ss" field.
func DistrictSsLTE(v string) predicate.Location {
	return predicate.Location(sql.FieldLTE(FieldDistrictSs, v))
}

// DistrictSsContains applies the Contains predicate on the "district_ss" field.
func DistrictSsContains(v string) predicate.Location {
	return predicate.Location(sql.FieldContains(FieldDistrictSs, v))
}

// DistrictSsHasPrefix applies the HasPrefix predicate on the "district_ss" field.
func DistrictSsHasPrefix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasPrefix(FieldDistrictSs, v))
}

// DistrictSsHasSuffix applies the HasSuffix predicate on the "district_ss" field.
func DistrictSsHasSuffix(v string) predicate.Location {
	return predicate.Location(sql.FieldHasSuffix(FieldDistrictSs, v))
}

// DistrictSsEqualFold applies the EqualFold predicate on the "district_ss" field.
func DistrictSsEqualFold(v string) predicate.Location {
	return predicate.Location(sql.FieldEqualFold(FieldDistrictSs, v))
}

// DistrictSsContainsFold applies the ContainsFold predicate on the "district_ss" field.
func DistrictSsContainsFold(v string) predicate.Location {
	return predicate.Location(sql.FieldContainsFold(FieldDistrictSs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Location) predicate.Location {
	return predicate.Location(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Location) predicate.Location {
	return predicate.Location(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Location) predicate.Location {
	return predicate.Location(sql.NotPredicates(p))
}
