// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LocationsColumns holds the columns for the "locations" table.
	LocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "chrononym", Type: field.TypeString},
		{Name: "definition", Type: field.TypeString},
		{Name: "context", Type: field.TypeString},
		{Name: "district", Type: field.TypeString},
		{Name: "selsovet", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "longitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "year", Type: field.TypeString},
		{Name: "district_ss", Type: field.TypeString},
	}
	// LocationsTable holds the schema information for the "locations" table.
	LocationsTable = &schema.Table{
		Name:       "locations",
		Columns:    LocationsColumns,
		PrimaryKey: []*schema.Column{LocationsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LocationsTable,
	}
)

func init() {
}
