// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zeshi09/dialectApi/ent/location"
)

// LocationCreate is the builder for creating a Location entity.
type LocationCreate struct {
	config
	mutation *LocationMutation
	hooks    []Hook
}

// SetChrononym sets the "chrononym" field.
func (_c *LocationCreate) SetChrononym(v string) *LocationCreate {
	_c.mutation.SetChrononym(v)
	return _c
}

// SetDefinition sets the "definition" field.
func (_c *LocationCreate) SetDefinition(v string) *LocationCreate {
	_c.mutation.SetDefinition(v)
	return _c
}

// SetContext sets the "context" field.
func (_c *LocationCreate) SetContext(v string) *LocationCreate {
	_c.mutation.SetContext(v)
	return _c
}

// SetDistrict sets the "district" field.
func (_c *LocationCreate) SetDistrict(v string) *LocationCreate {
	_c.mutation.SetDistrict(v)
	return _c
}

// SetSelsovet sets the "selsovet" field.
func (_c *LocationCreate) SetSelsovet(v string) *LocationCreate {
	_c.mutation.SetSelsovet(v)
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *LocationCreate) SetLatitude(v float64) *LocationCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *LocationCreate) SetNillableLatitude(v *float64) *LocationCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *LocationCreate) SetLongitude(v float64) *LocationCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *LocationCreate) SetNillableLongitude(v *float64) *LocationCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetComment sets the "comment" field.
func (_c *LocationCreate) SetComment(v string) *LocationCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *LocationCreate) SetNillableComment(v *string) *LocationCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetYear sets the "year" field.
func (_c *LocationCreate) SetYear(v string) *LocationCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetDistrictSs sets the "district_ss" field.
func (_c *LocationCreate) SetDistrictSs(v string) *LocationCreate {
	_c.mutation.SetDistrictSs(v)
	return _c
}

// Mutation returns the LocationMutation object of the builder.
func (_c *LocationCreate) Mutation() *LocationMutation {
	return _c.mutation
}

// Save creates the Location in the database.
func (_c *LocationCreate) Save(ctx context.Context) (*Location, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LocationCreate) SaveX(ctx context.Context) *Location {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LocationCreate) check() error {
	if _, ok := _c.mutation.Chrononym(); !ok {
		return &ValidationError{Name: "chrononym", err: errors.New(`ent: missing required field "Location.chrononym"`)}
	}
	if v, ok := _c.mutation.Chrononym(); ok {
		if err := location.ChrononymValidator(v); err != nil {
			return &ValidationError{Name: "chrononym", err: fmt.Errorf(`ent: validator failed for field "Location.chrononym": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Definition(); !ok {
		return &ValidationError{Name: "definition", err: errors.New(`ent: missing required field "Location.definition"`)}
	}
	if v, ok := _c.mutation.Definition(); ok {
		if err := location.DefinitionValidator(v); err != nil {
			return &ValidationError{Name: "definition", err: fmt.Errorf(`ent: validator failed for field "Location.definition": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Context(); !ok {
		return &ValidationError{Name: "context", err: errors.New(`ent: missing required field "Location.context"`)}
	}
	if v, ok := _c.mutation.Context(); ok {
		if err := location.ContextValidator(v); err != nil {
			return &ValidationError{Name: "context", err: fmt.Errorf(`ent: validator failed for field "Location.context": %w`, err)}
		}
	}
	if _, ok := _c.mutation.District(); !ok {
		return &ValidationError{Name: "district", err: errors.New(`ent: missing required field "Location.district"`)}
	}
	if v, ok := _c.mutation.District(); ok {
		if err := location.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "Location.district": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Selsovet(); !ok {
		return &ValidationError{Name: "selsovet", err: errors.New(`ent: missing required field "Location.selsovet"`)}
	}
	if v, ok := _c.mutation.Selsovet(); ok {
		if err := location.SelsovetValidator(v); err != nil {
			return &ValidationError{Name: "selsovet", err: fmt.Errorf(`ent: validator failed for field "Location.selsovet": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "Location.year"`)}
	}
	if v, ok := _c.mutation.Year(); ok {
		if err := location.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Location.year": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DistrictSs(); !ok {
		return &ValidationError{Name: "district_ss", err: errors.New(`ent: missing required field "Location.district_ss"`)}
	}
	if v, ok := _c.mutation.DistrictSs(); ok {
		if err := location.DistrictSsValidator(v); err != nil {
			return &ValidationError{Name: "district_ss", err: fmt.Errorf(`ent: validator failed for field "Location.district_ss": %w`, err)}
		}
	}
	return nil
}

func (_c *LocationCreate) sqlSave(ctx context.Context) (*Location, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LocationCreate) createSpec() (*Location, *sqlgraph.CreateSpec) {
	var (
		_node = &Location{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(location.Table, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Chrononym(); ok {
		_spec.SetField(location.FieldChrononym, field.TypeString, value)
		_node.Chrononym = value
	}
	if value, ok := _c.mutation.Definition(); ok {
		_spec.SetField(location.FieldDefinition, field.TypeString, value)
		_node.Definition = value
	}
	if value, ok := _c.mutation.Context(); ok {
		_spec.SetField(location.FieldContext, field.TypeString, value)
		_node.Context = value
	}
	if value, ok := _c.mutation.District(); ok {
		_spec.SetField(location.FieldDistrict, field.TypeString, value)
		_node.District = value
	}
	if value, ok := _c.mutation.Selsovet(); ok {
		_spec.SetField(location.FieldSelsovet, field.TypeString, value)
		_node.Selsovet = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(location.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(location.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(location.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(location.FieldYear, field.TypeString, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.DistrictSs(); ok {
		_spec.SetField(location.FieldDistrictSs, field.TypeString, value)
		_node.DistrictSs = value
	}
	return _node, _spec
}

// LocationCreateBulk is the builder for creating many Location entities in bulk.
type LocationCreateBulk struct {
	config
	err      error
	builders []*LocationCreate
}

// Save creates the Location entities in the database.
func (_c *LocationCreateBulk) Save(ctx context.Context) ([]*Location, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Location, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LocationCreateBulk) SaveX(ctx context.Context) []*Location {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
