// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/zeshi09/dialectApi/ent/location"
)

// Location is the model entity for the Location schema.
type Location struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Chrononym holds the value of the "chrononym" field.
	Chrononym string `json:"chrononym,omitempty"`
	// Definition holds the value of the "definition" field.
	Definition string `json:"definition,omitempty"`
	// Context holds the value of the "context" field.
	Context string `json:"context,omitempty"`
	// District holds the value of the "district" field.
	District string `json:"district,omitempty"`
	// Selsovet holds the value of the "selsovet" field.
	Selsovet string `json:"selsovet,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude float64 `json:"longitude,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment string `json:"comment,omitempty"`
	// Year holds the value of the "year" field.
	Year string `json:"year,omitempty"`
	// DistrictSs holds the value of the "district_ss" field.
	DistrictSs   string `json:"district_ss,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Location) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case location.FieldLatitude, location.FieldLongitude:
			values[i] = new(sql.NullFloat64)
		case location.FieldID:
			values[i] = new(sql.NullInt64)
		case location.FieldChrononym, location.FieldDefinition, location.FieldContext, location.FieldDistrict, location.FieldSelsovet, location.FieldComment, location.FieldYear, location.FieldDistrictSs:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Location fields.
func (_m *Location) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case location.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case location.FieldChrononym:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chrononym", values[i])
			} else if value.Valid {
				_m.Chrononym = value.String
			}
		case location.FieldDefinition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field definition", values[i])
			} else if value.Valid {
				_m.Definition = value.String
			}
		case location.FieldContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value.Valid {
				_m.Context = value.String
			}
		case location.FieldDistrict:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field district", values[i])
			} else if value.Valid {
				_m.District = value.String
			}
		case location.FieldSelsovet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field selsovet", values[i])
			} else if value.Valid {
				_m.Selsovet = value.String
			}
		case location.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = value.Float64
			}
		case location.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = value.Float64
			}
		case location.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		case location.FieldYear:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = value.String
			}
		case location.FieldDistrictSs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field district_ss", values[i])
			} else if value.Valid {
				_m.DistrictSs = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Location.
// This includes values selected through modifiers, order, etc.
func (_m *Location) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Location.
// Note that you need to call Location.Unwrap() before calling this method if this Location
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Location) Update() *LocationUpdateOne {
	return NewLocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Location entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Location) Unwrap() *Location {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Location is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Location) String() string {
	var builder strings.Builder
	builder.WriteString("Location(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chrononym=")
	builder.WriteString(_m.Chrononym)
	builder.WriteString(", ")
	builder.WriteString("definition=")
	builder.WriteString(_m.Definition)
	builder.WriteString(", ")
	builder.WriteString("context=")
	builder.WriteString(_m.Context)
	builder.WriteString(", ")
	builder.WriteString("district=")
	builder.WriteString(_m.District)
	builder.WriteString(", ")
	builder.WriteString("selsovet=")
	builder.WriteString(_m.Selsovet)
	builder.WriteString(", ")
	builder.WriteString("latitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Latitude))
	builder.WriteString(", ")
	builder.WriteString("longitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Longitude))
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteString(", ")
	builder.WriteString("year=")
	builder.WriteString(_m.Year)
	builder.WriteString(", ")
	builder.WriteString("district_ss=")
	builder.WriteString(_m.DistrictSs)
	builder.WriteByte(')')
	return builder.String()
}

// Locations is a parsable slice of Location.
type Locations []*Location
