// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zeshi09/dialectApi/ent/location"
	"github.com/zeshi09/dialectApi/ent/predicate"
)

// LocationUpdate is the builder for updating Location entities.
type LocationUpdate struct {
	config
	hooks    []Hook
	mutation *LocationMutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (_u *LocationUpdate) Where(ps ...predicate.Location) *LocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChrononym sets the "chrononym" field.
func (_u *LocationUpdate) SetChrononym(v string) *LocationUpdate {
	_u.mutation.SetChrononym(v)
	return _u
}

// SetNillableChrononym sets the "chrononym" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableChrononym(v *string) *LocationUpdate {
	if v != nil {
		_u.SetChrononym(*v)
	}
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *LocationUpdate) SetDefinition(v string) *LocationUpdate {
	_u.mutation.SetDefinition(v)
	return _u
}

// SetNillableDefinition sets the "definition" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableDefinition(v *string) *LocationUpdate {
	if v != nil {
		_u.SetDefinition(*v)
	}
	return _u
}

// SetContext sets the "context" field.
func (_u *LocationUpdate) SetContext(v string) *LocationUpdate {
	_u.mutation.SetContext(v)
	return _u
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableContext(v *string) *LocationUpdate {
	if v != nil {
		_u.SetContext(*v)
	}
	return _u
}

// SetDistrict sets the "district" field.
func (_u *LocationUpdate) SetDistrict(v string) *LocationUpdate {
	_u.mutation.SetDistrict(v)
	return _u
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableDistrict(v *string) *LocationUpdate {
	if v != nil {
		_u.SetDistrict(*v)
	}
	return _u
}

// SetSelsovet sets the "selsovet" field.
func (_u *LocationUpdate) SetSelsovet(v string) *LocationUpdate {
	_u.mutation.SetSelsovet(v)
	return _u
}

// SetNillableSelsovet sets the "selsovet" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableSelsovet(v *string) *LocationUpdate {
	if v != nil {
		_u.SetSelsovet(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *LocationUpdate) SetLatitude(v float64) *LocationUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableLatitude(v *float64) *LocationUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *LocationUpdate) AddLatitude(v float64) *LocationUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *LocationUpdate) ClearLatitude() *LocationUpdate {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *LocationUpdate) SetLongitude(v float64) *LocationUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableLongitude(v *float64) *LocationUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *LocationUpdate) AddLongitude(v float64) *LocationUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *LocationUpdate) ClearLongitude() *LocationUpdate {
	_u.mutation.ClearLongitude()
	return _u
}

// SetComment sets the "comment" field.
func (_u *LocationUpdate) SetComment(v string) *LocationUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableComment(v *string) *LocationUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *LocationUpdate) ClearComment() *LocationUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetYear sets the "year" field.
func (_u *LocationUpdate) SetYear(v string) *LocationUpdate {
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableYear(v *string) *LocationUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// SetDistrictSs sets the "district_ss" field.
func (_u *LocationUpdate) SetDistrictSs(v string) *LocationUpdate {
	_u.mutation.SetDistrictSs(v)
	return _u
}

// SetNillableDistrictSs sets the "district_ss" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableDistrictSs(v *string) *LocationUpdate {
	if v != nil {
		_u.SetDistrictSs(*v)
	}
	return _u
}

// Mutation returns the LocationMutation object of the builder.
func (_u *LocationUpdate) Mutation() *LocationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationUpdate) check() error {
	if v, ok := _u.mutation.Chrononym(); ok {
		if err := location.ChrononymValidator(v); err != nil {
			return &ValidationError{Name: "chrononym", err: fmt.Errorf(`ent: validator failed for field "Location.chrononym": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Definition(); ok {
		if err := location.DefinitionValidator(v); err != nil {
			return &ValidationError{Name: "definition", err: fmt.Errorf(`ent: validator failed for field "Location.definition": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Context(); ok {
		if err := location.ContextValidator(v); err != nil {
			return &ValidationError{Name: "context", err: fmt.Errorf(`ent: validator failed for field "Location.context": %w`, err)}
		}
	}
	if v, ok := _u.mutation.District(); ok {
		if err := location.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "Location.district": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Selsovet(); ok {
		if err := location.SelsovetValidator(v); err != nil {
			return &ValidationError{Name: "selsovet", err: fmt.Errorf(`ent: validator failed for field "Location.selsovet": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Year(); ok {
		if err := location.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Location.year": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DistrictSs(); ok {
		if err := location.DistrictSsValidator(v); err != nil {
			return &ValidationError{Name: "district_ss", err: fmt.Errorf(`ent: validator failed for field "Location.district_ss": %w`, err)}
		}
	}
	return nil
}

func (_u *LocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chrononym(); ok {
		_spec.SetField(location.FieldChrononym, field.TypeString, value)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(location.FieldDefinition, field.TypeString, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(location.FieldContext, field.TypeString, value)
	}
	if value, ok := _u.mutation.District(); ok {
		_spec.SetField(location.FieldDistrict, field.TypeString, value)
	}
	if value, ok := _u.mutation.Selsovet(); ok {
		_spec.SetField(location.FieldSelsovet, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(location.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(location.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(location.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(location.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(location.FieldYear, field.TypeString, value)
	}
	if value, ok := _u.mutation.DistrictSs(); ok {
		_spec.SetField(location.FieldDistrictSs, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LocationUpdateOne is the builder for updating a single Location entity.
type LocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationMutation
}

// SetChrononym sets the "chrononym" field.
func (_u *LocationUpdateOne) SetChrononym(v string) *LocationUpdateOne {
	_u.mutation.SetChrononym(v)
	return _u
}

// SetNillableChrononym sets the "chrononym" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableChrononym(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetChrononym(*v)
	}
	return _u
}

// SetDefinition sets the "definition" field.
func (_u *LocationUpdateOne) SetDefinition(v string) *LocationUpdateOne {
	_u.mutation.SetDefinition(v)
	return _u
}

// SetNillableDefinition sets the "definition" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableDefinition(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetDefinition(*v)
	}
	return _u
}

// SetContext sets the "context" field.
func (_u *LocationUpdateOne) SetContext(v string) *LocationUpdateOne {
	_u.mutation.SetContext(v)
	return _u
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableContext(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetContext(*v)
	}
	return _u
}

// SetDistrict sets the "district" field.
func (_u *LocationUpdateOne) SetDistrict(v string) *LocationUpdateOne {
	_u.mutation.SetDistrict(v)
	return _u
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableDistrict(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetDistrict(*v)
	}
	return _u
}

// SetSelsovet sets the "selsovet" field.
func (_u *LocationUpdateOne) SetSelsovet(v string) *LocationUpdateOne {
	_u.mutation.SetSelsovet(v)
	return _u
}

// SetNillableSelsovet sets the "selsovet" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableSelsovet(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetSelsovet(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *LocationUpdateOne) SetLatitude(v float64) *LocationUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableLatitude(v *float64) *LocationUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *LocationUpdateOne) AddLatitude(v float64) *LocationUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *LocationUpdateOne) ClearLatitude() *LocationUpdateOne {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *LocationUpdateOne) SetLongitude(v float64) *LocationUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableLongitude(v *float64) *LocationUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *LocationUpdateOne) AddLongitude(v float64) *LocationUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *LocationUpdateOne) ClearLongitude() *LocationUpdateOne {
	_u.mutation.ClearLongitude()
	return _u
}

// SetComment sets the "comment" field.
func (_u *LocationUpdateOne) SetComment(v string) *LocationUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableComment(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *LocationUpdateOne) ClearComment() *LocationUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetYear sets the "year" field.
func (_u *LocationUpdateOne) SetYear(v string) *LocationUpdateOne {
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableYear(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// SetDistrictSs sets the "district_ss" field.
func (_u *LocationUpdateOne) SetDistrictSs(v string) *LocationUpdateOne {
	_u.mutation.SetDistrictSs(v)
	return _u
}

// SetNillableDistrictSs sets the "district_ss" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableDistrictSs(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetDistrictSs(*v)
	}
	return _u
}

// Mutation returns the LocationMutation object of the builder.
func (_u *LocationUpdateOne) Mutation() *LocationMutation {
	return _u.mutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (_u *LocationUpdateOne) Where(ps ...predicate.Location) *LocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LocationUpdateOne) Select(field string, fields ...string) *LocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Location entity.
func (_u *LocationUpdateOne) Save(ctx context.Context) (*Location, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationUpdateOne) SaveX(ctx context.Context) *Location {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationUpdateOne) check() error {
	if v, ok := _u.mutation.Chrononym(); ok {
		if err := location.ChrononymValidator(v); err != nil {
			return &ValidationError{Name: "chrononym", err: fmt.Errorf(`ent: validator failed for field "Location.chrononym": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Definition(); ok {
		if err := location.DefinitionValidator(v); err != nil {
			return &ValidationError{Name: "definition", err: fmt.Errorf(`ent: validator failed for field "Location.definition": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Context(); ok {
		if err := location.ContextValidator(v); err != nil {
			return &ValidationError{Name: "context", err: fmt.Errorf(`ent: validator failed for field "Location.context": %w`, err)}
		}
	}
	if v, ok := _u.mutation.District(); ok {
		if err := location.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "Location.district": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Selsovet(); ok {
		if err := location.SelsovetValidator(v); err != nil {
			return &ValidationError{Name: "selsovet", err: fmt.Errorf(`ent: validator failed for field "Location.selsovet": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Year(); ok {
		if err := location.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Location.year": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DistrictSs(); ok {
		if err := location.DistrictSsValidator(v); err != nil {
			return &ValidationError{Name: "district_ss", err: fmt.Errorf(`ent: validator failed for field "Location.district_ss": %w`, err)}
		}
	}
	return nil
}

func (_u *LocationUpdateOne) sqlSave(ctx context.Context) (_node *Location, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Location.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, location.FieldID)
		for _, f := range fields {
			if !location.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != location.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chrononym(); ok {
		_spec.SetField(location.FieldChrononym, field.TypeString, value)
	}
	if value, ok := _u.mutation.Definition(); ok {
		_spec.SetField(location.FieldDefinition, field.TypeString, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(location.FieldContext, field.TypeString, value)
	}
	if value, ok := _u.mutation.District(); ok {
		_spec.SetField(location.FieldDistrict, field.TypeString, value)
	}
	if value, ok := _u.mutation.Selsovet(); ok {
		_spec.SetField(location.FieldSelsovet, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(location.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(location.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(location.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(location.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(location.FieldYear, field.TypeString, value)
	}
	if value, ok := _u.mutation.DistrictSs(); ok {
		_spec.SetField(location.FieldDistrictSs, field.TypeString, value)
	}
	_node = &Location{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
