// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/zeshi09/dialectApi/ent/location"
	"github.com/zeshi09/dialectApi/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	locationFields := schema.Location{}.Fields()
	_ = locationFields
	// locationDescChrononym is the schema descriptor for chrononym field.
	locationDescChrononym := locationFields[0].Descriptor()
	// location.ChrononymValidator is a validator for the "chrononym" field. It is called by the builders before save.
	location.ChrononymValidator = locationDescChrononym.Validators[0].(func(string) error)
	// locationDescDefinition is the schema descriptor for definition field.
	locationDescDefinition := locationFields[1].Descriptor()
	// location.DefinitionValidator is a validator for the "definition" field. It is called by the builders before save.
	location.DefinitionValidator = locationDescDefinition.Validators[0].(func(string) error)
	// locationDescContext is the schema descriptor for context field.
	locationDescContext := locationFields[2].Descriptor()
	// location.ContextValidator is a validator for the "context" field. It is called by the builders before save.
	location.ContextValidator = locationDescContext.Validators[0].(func(string) error)
	// locationDescDistrict is the schema descriptor for district field.
	locationDescDistrict := locationFields[3].Descriptor()
	// location.DistrictValidator is a validator for the "district" field. It is called by the builders before save.
	location.DistrictValidator = locationDescDistrict.Validators[0].(func(string) error)
	// locationDescSelsovet is the schema descriptor for selsovet field.
	locationDescSelsovet := locationFields[4].Descriptor()
	// location.SelsovetValidator is a validator for the "selsovet" field. It is called by the builders before save.
	location.SelsovetValidator = locationDescSelsovet.Validators[0].(func(string) error)
	// locationDescYear is the schema descriptor for year field.
	locationDescYear := locationFields[8].Descriptor()
	// location.YearValidator is a validator for the "year" field. It is called by the builders before save.
	location.YearValidator = locationDescYear.Validators[0].(func(string) error)
	// locationDescDistrictSs is the schema descriptor for district_ss field.
	locationDescDistrictSs := locationFields[9].Descriptor()
	// location.DistrictSsValidator is a validator for the "district_ss" field. It is called by the builders before save.
	location.DistrictSsValidator = locationDescDistrictSs.Validators[0].(func(string) error)
}
